services:
  backend:
    image: claudiaea/whysoserious-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
    restart: unless-stopped   

  frontend:
    image: claudiaea/whysoserious-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
